spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/dev_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    out-of-order: true
server:
  port: 9999
